- hosts: localhost
  become: true
  vars: 
    source_key: "home/jacob/.ssh/github_com_ed25519"
    dest_key: "home/jacob/.ssh/github_com_ed25519"
  tasks:
  - name: Install Basic Packages
    community.general.pacman:
      name:
        - zsh
        - github-cli
        - openssh
        - fzf
        - pv
        - clang
        - llvm
        - rust
        - lm_sensors
        - psutils
        - neofetch
        - htop
        - bashtop
        - imagemagick
        - jq
        - bat
        - ripgrep
        - bat-extras
        - lsd
        - figlet
        - tmux
        - stow
  - name: Make folders
    become_user: jacob
    ansible.builtin.shell: mkdir bin Downloads .dotfiles
  - name: Clone keys
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/JacobStephenson97/ansible.git'
      dest: ~/keys
  - name: mv keys
    become_user: jacob
    shell: |
      mv ~/keys/.ssh ./
#   - name: Ensure .ssh directory exists.
#     become_user: root
#     file:
#       dest: "{{ dest_key | dirname }}"
#       mode: 0700
#       state: directory

#   - name: Install ssh key
#     become_user: root
#     copy:
#       src: "{{ source_key }}"
#       dest: "{{ dest_key }}"
#       mode: 0600

  - name: Set authorized key took from file
    authorized_key:
      user: "{{ lookup('env', 'USER') }}"
      state: present
      key: "{{ lookup('env', 'HOME') }}/.ssh/github_com_ed25519.pub"


  - name: Clone yay
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://aur.archlinux.org/yay.git'
      dest: /home/jacob/yay
  - name: Install yay
    become_user: jacob
    ansible.builtin.shell: cd yay && makepkg -si --noconfirm && rm -rf ~/yay
    
  - name: Run oh-my-zsh install script
    become_user: jacob
    ansible.builtin.shell: source <(curl -fsSL http://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --noconfirm
    
  - name: Install zsh-theme-powerlevel10k-git package
    become_user: jacob
    ansible.builtin.shell: yay -S --noconfirm zsh-theme-powerlevel10k-git

  - name: Clone dotfiles
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/JacobStephenson97/.dotfiles.git'
      dest: ~/.dotfiles
  - name: stow dotfiles
    shell: rm .zshrc && cd .dotfiles && stow .
  - name: change default shell
    shell: chsh -s /bin/zsh jacob
    
  - name: Get auto-suggestions
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  - name: Get Syntax Highlighting
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      
  #May not be necessary
  - name: Export correct Term
    ansible.builtin.shell: echo "export TERM=xterm-256color" >> .zshrc
    
    
  #TMUX
  - name: Clone yay
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: ~/.tmux/plugins/tpm
   
      
