- hosts: localhost
  become: true
  tasks:
  - name: Install Basic Packages
    community.general.pacman:
      name:
        - zsh
        - github-cli
        - fzf
        - pv
        - clang
        - llvm
        - rust
        - lm_sensors
        - psutils
        - neofetch
        - htop
        - bashtop
        - imagemagick
        - jq
  - name: Make bin/downloads
    ansible.builtin.shell: mkdir bin Downloads
  - name: Clone yay
    become: yes
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://aur.archlinux.org/yay.git'
      dest: /home/jacob/yay
  - name: Install yay
    become: yes
    become_user: jacob
    ansible.builtin.shell: cd yay && makepkg -si --noconfirm && rm -rf ~/yay
    
      
