- hosts: localhost
  become: true
  tasks:
  - name: Install Basic Packages
    community.general.pacman:
      name:
        - zsh
        - github-cli
        - openssh
        - fzf
        - pv
        - clang
        - llvm
        - rust
        - lm_sensors
        - psutils
        - neofetch
        - htop
        - bashtop
        - imagemagick
        - jq
        - bat
        - ripgrep
        - bat-extras
        - lsd
        - figlet
        - tmux
  - name: Make bin/downloads
    ansible.builtin.shell: mkdir bin Downloads
  - name: Clone yay
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://aur.archlinux.org/yay.git'
      dest: /home/jacob/yay
  - name: Install yay
    become_user: jacob
    ansible.builtin.shell: cd yay && makepkg -si --noconfirm && rm -rf ~/yay
    
  - name: Run oh-my-zsh install script
    become_user: jacob
    ansible.builtin.shell: source <(curl -fsSL http://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --noconfirm
    
  - name: Install zsh-theme-powerlevel10k-git package
    become_user: jacob
    ansible.builtin.shell: yay -S --noconfirm zsh-theme-powerlevel10k-git

    #Can do this better later
  - name: Get zsh dotfile
    become_user: jacob
    ansible.builtin.shell: curl -s https://raw.githubusercontent.com/JacobStephenson97/.dotfiles/main/.zshrc > ~/.zshrc 
  - name: Get p10k dotfile
    become_user: jacob
    ansible.builtin.shell: curl -s https://raw.githubusercontent.com/JacobStephenson97/.dotfiles/main/.p10k.zsh > ~/.p10k.zsh
  - name: Get tmux
    become_user: jacob
    ansible.builtin.shell: curl -s https://raw.githubusercontent.com/JacobStephenson97/ansible/main/.tmux.conf > ~/.tmux.conf
    
  - name: change default shell
    ansible.builtin.shell: chsh -s /bin/zsh jacob
    
  - name: Get auto-suggestions
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  - name: Get Syntax Highlighting
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      
  #May not be necessary
  - name: Export correct Term
    ansible.builtin.shell: echo "export TERM=xterm-256color" >> .zshrc
    
    
  #TMUX
  - name: Clone yay
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: ~/.tmux/plugins/tpm
   
      
