- hosts: localhost
  become: true
  tasks:
  - name: Install zsh
    community.general.pacman:
      name: zsh
  - name: Install dev apps
    community.general.pacman:
      name: base-devel
      extra_args: --needed
  - name: Install git
    community.general.pacman:
      name: git
      extra_args: --needed
  - name: Make bin/downloads
    ansible.builtin.shell: mkdir bin Downloads
  - name: Clone and install yay
    become: yes
    become_user: jacob
    ansible.builtin.git: 
      repo: 'https://aur.archlinux.org/yay.git'
      dest: /home/jacob/yay
      
