- name: Install Basic Packages
  become: true
  become_user: root
  community.general.pacman:
    name:
      - zsh
      - github-cli
      - openssh
      - fzf
      - pv
      - clang
      - llvm
      - rust
      - lm_sensors
      - psutils
      - neofetch
      - htop
      - bashtop
      - imagemagick
      - jq
      - bat
      - ripgrep
      - bat-extras
      - lsd
      - figlet
      - tmux
      - stow
      - vim
      - keychain
  tags:
    - packages
    - core

- name: Make folders
  ansible.builtin.shell: mkdir ~/bin ~/downloads ~/.dotfiles
  ignore_errors: true
  tags:
    - core

- name: Clone yay
    become_user: jacob
    ansible.builtin.git:
      repo: 'https://aur.archlinux.org/yay.git'
      dest: /home/jacob/yay
  tags: yay
- name: Install yay
  become_user: jacob
  ansible.builtin.shell: cd ~/yay && makepkg -si --noconfirm && rm -rf ~/yay
  tags: yay