- name: Install Basic Packages
  become: true
  become_user: root
  community.general.pacman:
    name:
      - zsh
      - github-cli
      - openssh
      - fzf
      - pv
      - clang
      - llvm
      - rust
      - lm_sensors
      - psutils
      - neofetch
      - htop
      - bashtop
      - imagemagick
      - jq
      - bat
      - ripgrep
      - bat-extras
      - lsd
      - figlet
      - tmux
      - stow
      - vim
      - keychain
  tags:
    - packages
    - core

- name: Make folders
  ansible.builtin.shell: mkdir ~/bin ~/downloads ~/.dotfiles
  ignore_errors: true
  tags:
    - core
