- name: load ssh key
  shell: |
    eval "$(ssh-agent -s)"
    "ssh-add {{ dest_key }}"
- name: Reel Bot Project
  ansible.builtin.git:
    repo: "git@github.com:JacobStephenson97/reel-bot.git"
    bare: true
    dest: "{{ personal }}/reel-bot"
  tags:
    - personal-project
