- name: Reel Bot Project
  become_user: jacob
  ansible.builtin.git:
    repo: "git@github.com:JacobStephenson97/reel-bot.git"
    key_file: "~/.ssh/github_com_ed25519"
    dest: "{{ personal }}/reel-bot"
    accept_newhostkey: true
  tags:
    - personal-project
