- name: Run oh-my-zsh install script
  shell: source <(curl -fsSL http://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --noconfirm
  tags: zsh
  ignore_errors: true

- name: Install zsh-theme-powerlevel10k-git package
  shell: yay -S --noconfirm zsh-theme-powerlevel10k-git
  tags: zsh
  ignore_errors: true

- name: Get auto-suggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags: zsh
- name: Get Syntax Highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  tags: zsh

- name: change default shell
  become_user: root
  become: true
  shell: chsh -s /bin/zsh jacob
  tags: zsh
